parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../app/'
        exclude:
            - '../app/DependencyInjection/'
            - '../app/Entity/'
            - '../app/Kernel.php'

    App\Common\Infrastructure\Controller\ArgumentResolver\ValidatedRequestResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }
